#!/usr/bin/env bash
set -euo pipefail

APP_USER="${APP_DB_USER:-erp_app}"
APP_PASS="${APP_DB_PASSWORD:-change-me-app}"
APP_DB="${POSTGRES_DB:-erpwms}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${APP_USER}') THEN
    CREATE ROLE ${APP_USER} LOGIN PASSWORD '${APP_PASS}';
  END IF;
END \$\$;

DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${APP_DB}') THEN
    CREATE DATABASE ${APP_DB};
  END IF;
END \$\$;
SQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$APP_DB" <<SQL
GRANT CONNECT, TEMP ON DATABASE ${APP_DB} TO ${APP_USER};
GRANT USAGE, CREATE ON SCHEMA public TO ${APP_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${APP_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${APP_USER};
SQL
