FROM golang:1.23-alpine
WORKDIR /app

RUN apk add --no-cache bash ca-certificates curl

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go install github.com/pressly/goose/v3/cmd/goose@latest
RUN CGO_ENABLED=0 go build -o /app/seed ./cmd/seed

RUN mkdir -p /app/tools
COPY tools/migrate.sh /app/tools/migrate.sh
COPY tools/seed.sh /app/tools/seed.sh
RUN chmod +x /app/tools/*.sh

ENV PATH="/go/bin:${PATH}"
ENTRYPOINT ["/bin/bash","-lc"]
