// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (
  actor_user_id, actor_type, action, resource, resource_id, status,
  ip_hash, ua_hash, request_id, trace_id, metadata
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
`

type InsertAuditLogParams struct {
	ActorUserID pgtype.UUID
	ActorType   string
	Action      string
	Resource    string
	ResourceID  pgtype.Text
	Status      string
	IpHash      pgtype.Text
	UaHash      pgtype.Text
	RequestID   pgtype.Text
	TraceID     pgtype.Text
	Metadata    []byte
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ActorUserID,
		arg.ActorType,
		arg.Action,
		arg.Resource,
		arg.ResourceID,
		arg.Status,
		arg.IpHash,
		arg.UaHash,
		arg.RequestID,
		arg.TraceID,
		arg.Metadata,
	)
	return err
}
