// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshSession = `-- name: CreateRefreshSession :one
INSERT INTO refresh_sessions (user_id, refresh_hash, ua_hash, ip_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, refresh_hash, ua_hash, ip_hash, expires_at, revoked_at, created_at
`

type CreateRefreshSessionParams struct {
	UserID      pgtype.UUID
	RefreshHash string
	UaHash      pgtype.Text
	IpHash      pgtype.Text
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, createRefreshSession,
		arg.UserID,
		arg.RefreshHash,
		arg.UaHash,
		arg.IpHash,
		arg.ExpiresAt,
	)
	var i RefreshSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshHash,
		&i.UaHash,
		&i.IpHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshSessionByHash = `-- name: GetRefreshSessionByHash :one
SELECT id, user_id, refresh_hash, ua_hash, ip_hash, expires_at, revoked_at, created_at FROM refresh_sessions WHERE refresh_hash = $1
`

func (q *Queries) GetRefreshSessionByHash(ctx context.Context, refreshHash string) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, getRefreshSessionByHash, refreshHash)
	var i RefreshSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshHash,
		&i.UaHash,
		&i.IpHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeRefreshSessionByHash = `-- name: RevokeRefreshSessionByHash :exec
UPDATE refresh_sessions SET revoked_at = now() WHERE refresh_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshSessionByHash(ctx context.Context, refreshHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshSessionByHash, refreshHash)
	return err
}
