// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getIdempotency = `-- name: GetIdempotency :one
SELECT key, endpoint, actor_user_id, request_hash, response_json, created_at FROM idempotency_keys WHERE key = $1 AND endpoint = $2
`

type GetIdempotencyParams struct {
	Key      string
	Endpoint string
}

func (q *Queries) GetIdempotency(ctx context.Context, arg GetIdempotencyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotency, arg.Key, arg.Endpoint)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.Endpoint,
		&i.ActorUserID,
		&i.RequestHash,
		&i.ResponseJson,
		&i.CreatedAt,
	)
	return i, err
}

const insertIdempotency = `-- name: InsertIdempotency :exec
INSERT INTO idempotency_keys (key, endpoint, actor_user_id, request_hash, response_json)
VALUES ($1, $2, $3, $4, $5)
`

type InsertIdempotencyParams struct {
	Key          string
	Endpoint     string
	ActorUserID  pgtype.UUID
	RequestHash  string
	ResponseJson []byte
}

func (q *Queries) InsertIdempotency(ctx context.Context, arg InsertIdempotencyParams) error {
	_, err := q.db.Exec(ctx, insertIdempotency,
		arg.Key,
		arg.Endpoint,
		arg.ActorUserID,
		arg.RequestHash,
		arg.ResponseJson,
	)
	return err
}
