// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID          pgtype.UUID
	Ts          pgtype.Timestamptz
	ActorUserID pgtype.UUID
	ActorType   string
	Action      string
	Resource    string
	ResourceID  pgtype.Text
	Status      string
	IpHash      pgtype.Text
	UaHash      pgtype.Text
	RequestID   pgtype.Text
	TraceID     pgtype.Text
	Metadata    []byte
}

type IdempotencyKey struct {
	Key          string
	Endpoint     string
	ActorUserID  pgtype.UUID
	RequestHash  string
	ResponseJson []byte
	CreatedAt    pgtype.Timestamptz
}

type Item struct {
	ID      pgtype.UUID
	Sku     string
	Name    string
	Barcode pgtype.Text
	Uom     string
}

type Location struct {
	ID          pgtype.UUID
	WarehouseID pgtype.UUID
	Code        string
	Type        string
	Path        pgtype.Text
}

type OutboxEvent struct {
	ID        pgtype.UUID
	Topic     string
	Payload   []byte
	CreatedAt pgtype.Timestamptz
	SentAt    pgtype.Timestamptz
	Attempts  int32
	LastError pgtype.Text
}

type Permission struct {
	ID   pgtype.UUID
	Name string
}

type RefreshSession struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	RefreshHash string
	UaHash      pgtype.Text
	IpHash      pgtype.Text
	ExpiresAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type Role struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type RolePermission struct {
	RoleID       pgtype.UUID
	PermissionID pgtype.UUID
}

type StockBalance struct {
	ItemID       pgtype.UUID
	LocationID   pgtype.UUID
	QtyOnHand    pgtype.Numeric
	QtyAllocated pgtype.Numeric
	UpdatedAt    pgtype.Timestamptz
}

type StockLedger struct {
	MoveID         pgtype.UUID
	Ts             pgtype.Timestamptz
	ItemID         pgtype.UUID
	Qty            pgtype.Numeric
	FromLocationID pgtype.UUID
	ToLocationID   pgtype.UUID
	ReasonCode     string
	RefType        pgtype.Text
	RefID          pgtype.Text
	ActorUserID    pgtype.UUID
	RequestID      pgtype.Text
}

type User struct {
	ID           pgtype.UUID
	EmailHash    string
	EmailEnc     string
	EmailNonce   string
	EmailKeyID   string
	PasswordHash string
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UserRole struct {
	UserID pgtype.UUID
	RoleID pgtype.UUID
}

type Warehouse struct {
	ID   pgtype.UUID
	Code string
	Name string
}
