// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpOutboxAttempt = `-- name: BumpOutboxAttempt :exec
UPDATE outbox_events
SET attempts = attempts + 1, last_error = $2
WHERE id = $1
`

type BumpOutboxAttemptParams struct {
	ID        pgtype.UUID
	LastError pgtype.Text
}

func (q *Queries) BumpOutboxAttempt(ctx context.Context, arg BumpOutboxAttemptParams) error {
	_, err := q.db.Exec(ctx, bumpOutboxAttempt, arg.ID, arg.LastError)
	return err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :one
INSERT INTO outbox_events (topic, payload)
VALUES ($1, $2)
RETURNING id, topic, payload, created_at, sent_at, attempts, last_error
`

type InsertOutboxEventParams struct {
	Topic   string
	Payload []byte
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, insertOutboxEvent, arg.Topic, arg.Payload)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.Payload,
		&i.CreatedAt,
		&i.SentAt,
		&i.Attempts,
		&i.LastError,
	)
	return i, err
}

const listPendingOutboxEventsForUpdate = `-- name: ListPendingOutboxEventsForUpdate :many
SELECT id, topic, payload, created_at, sent_at, attempts, last_error FROM outbox_events
WHERE sent_at IS NULL
ORDER BY created_at
FOR UPDATE SKIP LOCKED
LIMIT $1
`

func (q *Queries) ListPendingOutboxEventsForUpdate(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, listPendingOutboxEventsForUpdate, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.Payload,
			&i.CreatedAt,
			&i.SentAt,
			&i.Attempts,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxSent = `-- name: MarkOutboxSent :exec
UPDATE outbox_events SET sent_at = now() WHERE id = $1
`

func (q *Queries) MarkOutboxSent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxSent, id)
	return err
}
