// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stock.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertOutboxEvent = `-- name: InsertOutboxEvent :one
INSERT INTO outbox_events (subject, payload)
VALUES ($1, $2)
RETURNING id, subject, payload, created_at, sent_at
`

type InsertOutboxEventParams struct {
	Subject string
	Payload []byte
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, insertOutboxEvent, arg.Subject, arg.Payload)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Payload,
		&i.CreatedAt,
		&i.SentAt,
	)
	return i, err
}

const listStockBalances = `-- name: ListStockBalances :many
SELECT sb.item_id, sb.location_id, sb.qty_on_hand, sb.qty_allocated, sb.updated_at
FROM stock_balance sb
ORDER BY sb.updated_at DESC
LIMIT $1 OFFSET $2
`

type ListStockBalancesParams struct {
	Limit  int32
	Offset int32
}

type ListStockBalancesRow struct {
	ItemID       pgtype.UUID
	LocationID   pgtype.UUID
	QtyOnHand    pgtype.Numeric
	QtyAllocated pgtype.Numeric
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) ListStockBalances(ctx context.Context, arg ListStockBalancesParams) ([]ListStockBalancesRow, error) {
	rows, err := q.db.Query(ctx, listStockBalances, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStockBalancesRow
	for rows.Next() {
		var i ListStockBalancesRow
		if err := rows.Scan(
			&i.ItemID,
			&i.LocationID,
			&i.QtyOnHand,
			&i.QtyAllocated,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
