// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email_hash, email_enc, email_nonce, email_key_id, password_hash, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email_hash, email_enc, email_nonce, email_key_id, password_hash, status, created_at, updated_at
`

type CreateUserParams struct {
	EmailHash    string
	EmailEnc     string
	EmailNonce   string
	EmailKeyID   string
	PasswordHash string
	Status       string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.EmailHash,
		arg.EmailEnc,
		arg.EmailNonce,
		arg.EmailKeyID,
		arg.PasswordHash,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmailHash,
		&i.EmailEnc,
		&i.EmailNonce,
		&i.EmailKeyID,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailHash = `-- name: GetUserByEmailHash :one
SELECT id, email_hash, email_enc, email_nonce, email_key_id, password_hash, status, created_at, updated_at FROM users WHERE email_hash = $1
`

func (q *Queries) GetUserByEmailHash(ctx context.Context, emailHash string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailHash, emailHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmailHash,
		&i.EmailEnc,
		&i.EmailNonce,
		&i.EmailKeyID,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email_hash, email_enc, email_nonce, email_key_id, password_hash, status, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmailHash,
		&i.EmailEnc,
		&i.EmailNonce,
		&i.EmailKeyID,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
